export const SET_PROPERTY_LOCATION = 'SET_PROPERTY_LOCATION';
export const SET_PROPERTY_ASYNC_CART = 'SET_PROPERTY_ASYNC_CART';
export const SET_PROPERTY_DATA = 'SET_PROPERTY_DATA';
export const SET_PROPERTY_SAVED_FILTER = 'SET_PROPERTY_SAVED_FILTER';
export const SET_AUCTION_SORT = 'SET_AUCTION_SORT';
