import { Media } from "../../Global/Media";

export const Categories = [
  {
    id: 1,
    image: Media.Icon_villa,
    // label: 'House, Villa, Bunglow, Appartment, and Flat',
    label: 'Residential',
    value: 'house_villa_bunglow_apartment_flat',
  },
  {
    id: 2,
    image: Media.Icon_land_2,
    // label:
    //   'Land, Agri, Commercial, Residential, Industrial, Farm Land & Estate',
    label: 'Land',
    value: 'land_agri_commercial_residential_industrial_farm',
  },
  {
    id: 3,
    image: Media.Icon_Appartment,
    // label: 'Commercial Building, Shop, and Office',
    label: 'Commercial',
    value: 'commercial_building_shop_office',
  },
  {
    id: 4,
    image: Media.Icon_Industrial_PropertyIndustrial_Property,
    // label: 'Industrial Property, Industrialshed, Godown, and Factory',
    label: 'Industrial',
    value: 'industrial_property_industrialshed_godown_factory',
  },
  {
    id: 5,
    image: Media.Icon_Machinery,
    label: 'Machinery',
    value: 'Machinery',
  },
  {
    id: 6,
    image: Media.Icon_Gold_jewellery,
    label: 'Gold Jewellery',
    value: 'gold',
  },
  {
    id: 7,
    image: Media.Icon_vehicle,
    label: 'Vehicle',
    value: 'Vehicle',
  },
  // {
  //   id: 8,
  //   image: Media.Icon_others,
  //   label: 'View all',
  //   value: 'Others',
  // },
  // {
  //   id: 9,
  //   image: Media.Icon_land,
  //   label: 'Land',
  //   value: 'Land',
  // },
  // {
  //   id: 10,
  //   image: Media.Icon_house,
  //   label: 'House',
  //   value: 'House',
  // },
  // {
  //   id: 11,
  //   image: Media.Icon_flat,
  //   label: 'Flat',
  //   value: 'Flat',
  // },
  // {
  //   id: 12,
  //   image: Media.Icon_villa,
  //   label: 'Villa',
  //   value: 'Villa',
  // },
  // {
  //   id: 9,
  //   image: Media.Icon_Appartment,
  //   label: 'Commercial',
  //   value: 'Commercial',
  // },
];
// export const Categories = [
//   {
//     id: 1,
//     image: Media.ActionCategory1,
//     label: 'House, Villa, Bunglow, Appartment, and Flat',
//     value: 'House, Villa, Bunglow, Appartment, and Flat',
//   },
//   {
//     id: 2,
//     image: Media.ActionCategory1,
//     label:
//       'Land, Agri, Commercial, Residential, Industrial, Farm Land & Estate',
//     value:
//       'Land, Agri, Commercial, Residential, Industrial, Farm Land & Estate',
//   },
//   {
//     id: 3,
//     image: Media.ActionCategory1,
//     label: 'Commercial Building, Shop, and Office',
//     value: 'Commercial Building, Shop, and Office',
//   },
//   {
//     id: 4,
//     image: Media.ActionCategory1,
//     label: 'Industrial Property, Industrialshed, Godown, and Factory',
//     value: 'Industrial Property, Industrialshed, Godown, and Factory',
//   },
//   {
//     id: 5,
//     image: Media.ActionCategory1,
//     label: 'Machinery',
//     value: 'Machinery',
//   },
//   {
//     id: 6,
//     image: Media.ActionCategory1,
//     label: 'Others',
//     value: 'Others',
//   },
//   {
//     id: 7,
//     image: Media.ActionCategory1,
//     label: 'Gold Jewellery',
//     value: 'Gold Jewellery',
//   },
//   {
//     id: 8,
//     image: Media.ActionCategory1,
//     label: 'Vehicle',
//     value: 'Vehicle',
//   },
//   {
//     id: 9,
//     image: Media.ActionCategory1,
//     label: 'Land',
//     value: 'Land',
//   },
//   {
//     id: 10,
//     image: Media.ActionCategory1,
//     label: 'House',
//     value: 'House',
//   },
//   {
//     id: 11,
//     image: Media.ActionCategory1,
//     label: 'Flat',
//     value: 'Flat',
//   },
//   {
//     id: 12,
//     image: Media.ActionCategory1,
//     label: 'Villa',
//     value: 'Villa',
//   },
//   {
//     id: 13,
//     image: Media.ActionCategory1,
//     label: 'Commercial',
//     value: 'Commercial',
//   },
//   {
//     id: 14,
//     image: Media.ActionCategory1,
//     label: 'Accessories',
//     value: 'Accessories',
//   },
//   {
//     id: 15,
//     image: Media.ActionCategory1,
//     label: 'Agricultural land',
//     value: 'Agricultural land',
//   },
//   {
//     id: 16,
//     image: Media.ActionCategory1,
//     label: 'Agriculture',
//     value: 'Agriculture',
//   },
//   {
//     id: 17,
//     image: Media.ActionCategory1,
//     label: 'Asset',
//     value: 'Asset',
//   },
//   {
//     id: 18,
//     image: Media.ActionCategory1,
//     label: 'Banquet Hall',
//     value: 'Banquet Hall',
//   },
//   {
//     id: 19,
//     image: Media.ActionCategory1,
//     label: 'Barge',
//     value: 'Barge',
//   },
//   {
//     id: 20,
//     image: Media.ActionCategory1,
//     label: 'Basement',
//     value: 'Basement',
//   },
//   {
//     id: 21,
//     image: Media.ActionCategory1,
//     label: 'Bricks',
//     value: 'Bricks',
//   },
//   {
//     id: 22,
//     image: Media.ActionCategory1,
//     label: 'Building',
//     value: 'Building',
//   },
//   {
//     id: 23,
//     image: Media.ActionCategory1,
//     label: 'Building-Shed With Plant and Machinery',
//     value: 'Building-Shed With Plant and Machinery',
//   },
//   {
//     id: 24,
//     image: Media.ActionCategory1,
//     label: 'Bunglow',
//     value: 'Bunglow',
//   },
//   {
//     id: 25,
//     image: Media.ActionCategory1,
//     label: 'Club House',
//     value: 'Club House',
//   },
//   {
//     id: 26,
//     image: Media.ActionCategory1,
//     label: 'Commercial Residential Plot',
//     value: 'Commercial Residential Plot',
//   },
//   {
//     id: 27,
//     image: Media.ActionCategory1,
//     label: 'Commercial Building',
//     value: 'Commercial Building',
//   },
//   {
//     id: 28,
//     image: Media.ActionCategory1,
//     label: 'Commercial cum Residential',
//     value: 'Commercial cum Residential',
//   },
//   {
//     id: 29,
//     image: Media.ActionCategory1,
//     label: 'Commercial cum Residential complex',
//     value: 'Commercial cum Residential complex',
//   },
//   {
//     id: 30,
//     image: Media.ActionCategory1,
//     label: 'Commercial cum Residential land and building',
//     value: 'Commercial cum Residential land and building',
//   },
//   {
//     id: 31,
//     image: Media.ActionCategory1,
//     label: 'Commercial Goods',
//     value: 'Commercial Goods',
//   },
//   {
//     id: 32,
//     image: Media.ActionCategory1,
//     label: 'Commercial Hall',
//     value: 'Commercial Hall',
//   },
//   {
//     id: 33,
//     image: Media.ActionCategory1,
//     label: 'Commercial land',
//     value: 'Commercial land',
//   },
//   {
//     id: 34,
//     image: Media.ActionCategory1,
//     label: 'Commercial Land And Building',
//     value: 'Commercial Land And Building',
//   },
//   {
//     id: 35,
//     image: Media.ActionCategory1,
//     label: 'Commercial Vacant Land',
//     value: 'Commercial Vacant Land',
//   },
//   {
//     id: 36,
//     image: Media.ActionCategory1,
//     label: 'Commerical',
//     value: 'Commerical',
//   },
//   {
//     id: 37,
//     image: Media.ActionCategory1,
//     label: 'Commodities',
//     value: 'Commodities',
//   },
//   {
//     id: 38,
//     image: Media.ActionCategory1,
//     label: 'Company',
//     value: 'Company',
//   },
//   {
//     id: 39,
//     image: Media.ActionCategory1,
//     label: 'Company as whole- As going concern',
//     value: 'Company as whole- As going concern',
//   },
//   {
//     id: 40,
//     image: Media.ActionCategory1,
//     label: 'Computer Hardware',
//     value: 'Computer Hardware',
//   },
//   {
//     id: 41,
//     image: Media.ActionCategory1,
//     label: 'Equipment',
//     value: 'Equipment',
//   },
//   {
//     id: 42,
//     image: Media.ActionCategory1,
//     label: 'Equipment And Plant and Machinery',
//     value: 'Equipment And Plant and Machinery',
//   },
//   {
//     id: 43,
//     image: Media.ActionCategory1,
//     label: 'Equipments',
//     value: 'Equipments',
//   },
//   {
//     id: 44,
//     image: Media.ActionCategory1,
//     label: 'Factory',
//     value: 'Factory',
//   },
//   {
//     id: 45,
//     image: Media.ActionCategory1,
//     label: 'Factory Building',
//     value: 'Factory Building',
//   },
//   {
//     id: 46,
//     image: Media.ActionCategory1,
//     label: 'Factory Land',
//     value: 'Factory Land',
//   },
//   {
//     id: 47,
//     image: Media.ActionCategory1,
//     label: 'Factory Land and Building',
//     value: 'Factory Land and Building',
//   },
//   {
//     id: 48,
//     image: Media.ActionCategory1,
//     label: 'Factory Land and Building and Plant and Machinery',
//     value: 'Factory Land and Building and Plant and Machinery',
//   },
//   {
//     id: 49,
//     image: Media.ActionCategory1,
//     label: 'Factory Land And Building With Machinery',
//     value: 'Factory Land And Building With Machinery',
//   },
//   {
//     id: 50,
//     image: Media.ActionCategory1,
//     label: 'Factory land and shed',
//     value: 'Factory land and shed',
//   },
//   {
//     id: 51,
//     image: Media.ActionCategory1,
//     label: 'Farm House',
//     value: 'Farm House',
//   },
//   {
//     id: 52,
//     image: Media.ActionCategory1,
//     label: 'Financial Assets',
//     value: 'Financial Assets',
//   },
//   {
//     id: 53,
//     image: Media.ActionCategory1,
//     label: 'Gala',
//     value: 'Gala',
//   },
//   {
//     id: 54,
//     image: Media.ActionCategory1,
//     label: 'Garage',
//     value: 'Garage',
//   },
//   {
//     id: 55,
//     image: Media.ActionCategory1,
//     label: 'Godown',
//     value: 'Godown',
//   },
//   {
//     id: 56,
//     image: Media.ActionCategory1,
//     label: 'Godown Building',
//     value: 'Godown Building',
//   },
//   {
//     id: 57,
//     image: Media.ActionCategory1,
//     label: 'Godown land',
//     value: 'Godown land',
//   },
//   {
//     id: 58,
//     image: Media.ActionCategory1,
//     label: 'Hotel',
//     value: 'Hotel',
//   },
//   {
//     id: 59,
//     image: Media.ActionCategory1,
//     label: 'House and Shop',
//     value: 'House and Shop',
//   },
//   {
//     id: 60,
//     image: Media.ActionCategory1,
//     label: 'Household Goods',
//     value: 'Household Goods',
//   },
//   {
//     id: 61,
//     image: Media.ActionCategory1,
//     label: 'Immovable And Movable Properties',
//     value: 'Immovable And Movable Properties',
//   },
//   {
//     id: 62,
//     image: Media.ActionCategory1,
//     label: 'Industrial Building',
//     value: 'Industrial Building',
//   },
//   {
//     id: 63,
//     image: Media.ActionCategory1,
//     label: 'Industrial Complex',
//     value: 'Industrial Complex',
//   },
//   {
//     id: 64,
//     image: Media.ActionCategory1,
//     label: 'INDUSTRIAL CUM RESIDENTIAL',
//     value: 'INDUSTRIAL CUM RESIDENTIAL',
//   },
//   {
//     id: 65,
//     image: Media.ActionCategory1,
//     label: 'Industrial land',
//     value: 'Industrial land',
//   },
//   {
//     id: 66,
//     image: Media.ActionCategory1,
//     label: 'Industrial Land And Building',
//     value: 'Industrial Land And Building',
//   },
//   {
//     id: 67,
//     image: Media.ActionCategory1,
//     label: 'Industrial Plot',
//     value: 'Industrial Plot',
//   },
//   {
//     id: 68,
//     image: Media.ActionCategory1,
//     label: 'Industrial plot AND Building',
//     value: 'Industrial plot AND Building',
//   },
//   {
//     id: 69,
//     image: Media.ActionCategory1,
//     label: 'Industrial Plot and Machinery',
//     value: 'Industrial Plot and Machinery',
//   },
//   {
//     id: 70,
//     image: Media.ActionCategory1,
//     label: 'Industrial Property',
//     value: 'Industrial Property',
//   },
//   {
//     id: 71,
//     image: Media.ActionCategory1,
//     label: 'Industrial Shed',
//     value: 'Industrial Shed',
//   },
//   {
//     id: 72,
//     image: Media.ActionCategory1,
//     label: 'Industrial Shed and Land',
//     value: 'Industrial Shed and Land',
//   },
//   {
//     id: 73,
//     image: Media.ActionCategory1,
//     label: 'Industrial sheds And Plant ND Machinery',
//     value: 'Industrial sheds And Plant ND Machinery',
//   },
//   {
//     id: 74,
//     image: Media.ActionCategory1,
//     label: 'Industrial site and Building',
//     value: 'Industrial site and Building',
//   },
//   {
//     id: 75,
//     image: Media.ActionCategory1,
//     label: 'Industrial waste land',
//     value: 'Industrial waste land',
//   },
//   {
//     id: 76,
//     image: Media.ActionCategory1,
//     label: 'IT Equipments',
//     value: 'IT Equipments',
//   },
//   {
//     id: 77,
//     image: Media.ActionCategory1,
//     label: 'Land And Building With Plant and Machinery',
//     value: 'Land And Building With Plant and Machinery',
//   },
//   {
//     id: 78,
//     image: Media.ActionCategory1,
//     label: 'Land And Building',
//     value: 'Land And Building',
//   },
//   {
//     id: 79,
//     image: Media.ActionCategory1,
//     label: 'Land and Building And Factory Shed',
//     value: 'Land and Building And Factory Shed',
//   },
//   {
//     id: 80,
//     image: Media.ActionCategory1,
//     label: 'land and Godown',
//     value: 'land and Godown',
//   },
//   {
//     id: 81,
//     image: Media.ActionCategory1,
//     label: 'Land and Hotel building',
//     value: 'Land and Hotel building',
//   },
//   {
//     id: 82,
//     image: Media.ActionCategory1,
//     label: 'Land and Residential Bungalow',
//     value: 'Land and Residential Bungalow',
//   },
//   {
//     id: 83,
//     image: Media.ActionCategory1,
//     label: 'Land And Shed',
//     value: 'Land And Shed',
//   },
//   {
//     id: 84,
//     image: Media.ActionCategory1,
//     label: 'Land with Commercial Shopping Building',
//     value: 'Land with Commercial Shopping Building',
//   },
//   {
//     id: 85,
//     image: Media.ActionCategory1,
//     label: 'land with Flat',
//     value: 'land with Flat',
//   },
//   {
//     id: 86,
//     image: Media.ActionCategory1,
//     label: 'Land Sheds Machinery',
//     value: 'Land Sheds Machinery',
//   },
//   {
//     id: 87,
//     image: Media.ActionCategory1,
//     label: 'Mall cum Multiplex',
//     value: 'Mall cum Multiplex',
//   },
//   {
//     id: 88,
//     image: Media.ActionCategory1,
//     label: 'Movable Assets',
//     value: 'Movable Assets',
//   },
//   {
//     id: 89,
//     image: Media.ActionCategory1,
//     label: 'Municipal House',
//     value: 'Municipal House',
//   },
//   {
//     id: 90,
//     image: Media.ActionCategory1,
//     label: 'NON AGRICULTURAL',
//     value: 'NON AGRICULTURAL',
//   },
//   {
//     id: 91,
//     image: Media.ActionCategory1,
//     label: 'Non Agricultural and Industrial',
//     value: 'Non Agricultural and Industrial',
//   },
//   {
//     id: 92,
//     image: Media.ActionCategory1,
//     label: 'Office',
//     value: 'Office',
//   },
//   {
//     id: 93,
//     image: Media.ActionCategory1,
//     label: 'Pent House',
//     value: 'Pent House',
//   },
//   {
//     id: 94,
//     image: Media.ActionCategory1,
//     label: 'Plant and Machinery',
//     value: 'Plant and Machinery',
//   },
//   {
//     id: 95,
//     image: Media.ActionCategory1,
//     label: 'Plot',
//     value: 'Plot',
//   },
//   {
//     id: 96,
//     image: Media.ActionCategory1,
//     label: 'plot and bungalow',
//     value: 'plot and bungalow',
//   },
//   {
//     id: 97,
//     image: Media.ActionCategory1,
//     label: 'Plot AND Plant building',
//     value: 'Plot AND Plant building',
//   },
//   {
//     id: 98,
//     image: Media.ActionCategory1,
//     label: 'Plot And Scrap',
//     value: 'Plot And Scrap',
//   },
//   {
//     id: 99,
//     image: Media.ActionCategory1,
//     label: 'Plot of Land - Building-Shed alongwith Plant AndMachinery',
//     value: 'Plot of Land - Building-Shed alongwith Plant AndMachinery',
//   },
//   {
//     id: 100,
//     image: Media.ActionCategory1,
//     label: 'PLOT or LAND AND Plant and Machinery',
//     value: 'PLOT or LAND AND Plant and Machinery',
//   },
//   {
//     id: 101,
//     image: Media.ActionCategory1,
//     label: 'PLOT With Machinery',
//     value: 'PLOT With Machinery',
//   },
//   {
//     id: 102,
//     image: Media.ActionCategory1,
//     label: 'Poultry Farm',
//     value: 'Poultry Farm',
//   },
//   {
//     id: 103,
//     image: Media.ActionCategory1,
//     label: 'Premises',
//     value: 'Premises',
//   },
//   {
//     id: 104,
//     image: Media.ActionCategory1,
//     label: 'Residential',
//     value: 'Residential',
//   },
//   {
//     id: 105,
//     image: Media.ActionCategory1,
//     label: 'Residential Building',
//     value: 'Residential Building',
//   },
//   {
//     id: 106,
//     image: Media.ActionCategory1,
//     label: 'Residential Bunglow',
//     value: 'Residential Bunglow',
//   },
//   {
//     id: 107,
//     image: Media.ActionCategory1,
//     label: 'Residential Cum Commercial',
//     value: 'Residential Cum Commercial',
//   },
//   {
//     id: 108,
//     image: Media.ActionCategory1,
//     label: 'Residential cum Industrial',
//     value: 'Residential cum Industrial',
//   },
//   {
//     id: 109,
//     image: Media.ActionCategory1,
//     label: 'Residential Flat',
//     value: 'Residential Flat',
//   },
//   {
//     id: 110,
//     image: Media.ActionCategory1,
//     label: 'Residential Home',
//     value: 'Residential Home',
//   },
//   {
//     id: 111,
//     image: Media.ActionCategory1,
//     label: 'residential land',
//     value: 'residential land',
//   },
//   {
//     id: 112,
//     image: Media.ActionCategory1,
//     label: 'Residential Land And Building',
//     value: 'Residential Land And Building',
//   },
//   {
//     id: 113,
//     image: Media.ActionCategory1,
//     label: 'Residential Plot',
//     value: 'Residential Plot',
//   },
//   {
//     id: 114,
//     image: Media.ActionCategory1,
//     label: 'Residential vacant land',
//     value: 'Residential vacant land',
//   },
//   {
//     id: 115,
//     image: Media.ActionCategory1,
//     label: 'Residential Vacant Plot',
//     value: 'Residential Vacant Plot',
//   },
//   {
//     id: 116,
//     image: Media.ActionCategory1,
//     label: 'Residential Vacant site',
//     value: 'Residential Vacant site',
//   },
//   {
//     id: 117,
//     image: Media.ActionCategory1,
//     label: 'RESORT',
//     value: 'RESORT',
//   },
//   {
//     id: 118,
//     image: Media.ActionCategory1,
//     label: 'Row House',
//     value: 'Row House',
//   },
//   {
//     id: 119,
//     image: Media.ActionCategory1,
//     label: 'Scrap',
//     value: 'Scrap',
//   },
//   {
//     id: 120,
//     image: Media.ActionCategory1,
//     label: 'Shares',
//     value: 'Shares',
//   },
//   {
//     id: 121,
//     image: Media.ActionCategory1,
//     label: 'Shed',
//     value: 'Shed',
//   },
//   {
//     id: 122,
//     image: Media.ActionCategory1,
//     label: 'Shed And Building',
//     value: 'Shed And Building',
//   },
//   {
//     id: 123,
//     image: Media.ActionCategory1,
//     label: 'Shop',
//     value: 'Shop',
//   },
//   {
//     id: 124,
//     image: Media.ActionCategory1,
//     label: 'SHOP And Residential',
//     value: 'SHOP And Residential',
//   },
//   {
//     id: 125,
//     image: Media.ActionCategory1,
//     label: 'Shop cum Flat',
//     value: 'Shop cum Flat',
//   },
//   {
//     id: 126,
//     image: Media.ActionCategory1,
//     label: 'shop cum residence',
//     value: 'shop cum residence',
//   },
//   {
//     id: 127,
//     image: Media.ActionCategory1,
//     label: 'Shopping Complex',
//     value: 'Shopping Complex',
//   },
//   {
//     id: 128,
//     image: Media.ActionCategory1,
//     label: 'Showroom',
//     value: 'Showroom',
//   },
//   {
//     id: 129,
//     image: Media.ActionCategory1,
//     label: 'Solvents',
//     value: 'Solvents',
//   },
//   {
//     id: 130,
//     image: Media.ActionCategory1,
//     label: 'Stock',
//     value: 'Stock',
//   },
//   {
//     id: 131,
//     image: Media.ActionCategory1,
//     label: 'Structure and Building along with Plant and Machinery',
//     value: 'Structure and Building along with Plant and Machinery',
//   },
//   {
//     id: 132,
//     image: Media.ActionCategory1,
//     label: 'Tehsil Garotha',
//     value: 'Tehsil Garotha',
//   },
//   {
//     id: 133,
//     image: Media.ActionCategory1,
//     label: 'Tenament',
//     value: 'Tenament',
//   },
//   {
//     id: 134,
//     image: Media.ActionCategory1,
//     label: 'theatre building',
//     value: 'theatre building',
//   },
//   {
//     id: 135,
//     image: Media.ActionCategory1,
//     label: 'Unit',
//     value: 'Unit',
//   },
//   {
//     id: 136,
//     image: Media.ActionCategory1,
//     label: 'Vacant House',
//     value: 'Vacant House',
//   },
//   {
//     id: 137,
//     image: Media.ActionCategory1,
//     label: 'Vacant Land',
//     value: 'Vacant Land',
//   },
//   {
//     id: 138,
//     image: Media.ActionCategory1,
//     label: 'Vacant Plot',
//     value: 'Vacant Plot',
//   },
//   {
//     id: 139,
//     image: Media.ActionCategory1,
//     label: 'Vacant site',
//     value: 'Vacant site',
//   },
//   {
//     id: 140,
//     image: Media.ActionCategory1,
//     label: 'VacantBarrenLand',
//     value: 'VacantBarrenLand',
//   },
//   {
//     id: 141,
//     image: Media.ActionCategory1,
//     label: 'Ware House and Land',
//     value: 'Ware House and Land',
//   },
//   {
//     id: 142,
//     image: Media.ActionCategory1,
//     label: 'Windmill',
//     value: 'Windmill',
//   },
// ];
