export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_FILTER_LOCATION = 'SET_FILTER_LOCATION';
export const SET_FILTER_REMOVE_ITEM = 'SET_FILTER_REMOVE_ITEM';
export const SET_AUTO_FILTER = 'SET_AUTO_FILTER';
export const SET_ASYNC_CART = 'SET_ASYNC_CART';
export const SET_EDIT_VISIBLE = 'SET_EDIT_VISIBLE';
//Auction
export const SET_AUCTION_USER_DATA = 'SET_AUCTION_USER_DATA';
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE';
