// export const AgentPlanData = [
//   {
//     id: 1,
//     plan_type: 'Basic',
//     plan_sub: '5X Response Rate',
//     plan_offer: '',
//     plan_prime: '10000',
//     plan_validity: 'Per Month',
//     plan_main_sub: '50 Number of Listings',
//     plan_sub_valid: '90 Days',
//   },
//   {
//     id: 2,
//     plan_type: 'Standard',
//     plan_sub: '5X Response Rate',
//     plan_offer: '',
//     plan_prime: '18000',
//     plan_validity: 'Per Month',
//     plan_main_sub: '100 Number of Listings',
//     plan_sub_valid: '120 Days',
//   },
//   {
//     id: 3,
//     plan_type: 'Premium',
//     plan_sub: '8X Response Rate',
//     plan_offer: '',
//     plan_prime: '25000',
//     plan_validity: 'Per Year',
//     plan_main_sub: '200 Number of Listings',
//     plan_sub_valid: '150 Days',
//   },
//   {
//     id: 4,
//     plan_type: 'Premium Plus',
//     plan_sub: '10X Response Rate',
//     plan_offer: '',
//     plan_prime: '40000',
//     plan_validity: 'Per Year',
//     plan_main_sub: '300 Number of Listings',
//     plan_sub_valid: '180 Days',
//   },
// ];

// export const OwnerPlanData = [
//   {
//     "id": 1,
//     "name": "Free",
//     "price": "",
//     "plan_price": "",
//     "period": "15",
//     "responseRate": "Standard",
//     "noOfListings": "1",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   },
//   {
//     "id": 2,
//     "name": "Basic",
//     "price": "2999",
//     "plan_price": "999",
//     "period": "30",
//     "responseRate": "2x",
//     "noOfListings": "2",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   },
//   {
//     "id": 3,
//     "name": "Standard",
//     "price": "4999",
//     "plan_price": "2999",
//     "period": "120",
//     "responseRate": "3x",
//     "noOfListings": "2",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   },
//   {
//     "id": 4,
//     "name": "Premium",
//     "price": "8999",
//     "plan_price": "5999",
//     "period": "180",
//     "responseRate": "5x",
//     "noOfListings": "2",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   },
//   {
//     "id": 5,
//     "name": "We Plus",
//     "price": "13999",
//     "plan_price": "9999",
//     "period": "250",
//     "responseRate": "8x",
//     "noOfListings": "2",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   },
//   {
//     "id": 6,
//     "name": "Premium Plus",
//     "price": "19999",
//     "plan_price": "14999",
//     "period": "365",
//     "responseRate": "10x",
//     "noOfListings": "2",
//     "whatsappNotification": true,
//     "highlightedHomePage": false,
//     "verifiedPropertyTag": false,
//     "relationshipManager": false,
//     "dedicatedSupport": false
//   }
// ];

// export const BuilderPlanData = [
//   {
//     id: 1,
//     plan_type: 'Basic',
//     plan_sub: 'Standard Response Rate',
//     plan_offer: '',
//     plan_prime: '1000',
//     plan_validity: 'Per Month',
//     plan_main_sub: '2 Number of Listings',
//     plan_sub_valid: '30 Days',
//   },
//   {
//     id: 2,
//     plan_type: 'Standard',
//     plan_sub: '3X Response Rate',
//     plan_offer: '',
//     plan_prime: '2000',
//     plan_validity: 'Per Month',
//     plan_main_sub: '2 Number of Listings',
//     plan_sub_valid: '120 Days',
//   },
//   {
//     id: 3,
//     plan_type: 'Premium',
//     plan_sub: '5X Response Rate',
//     plan_offer: '',
//     plan_prime: '3000',
//     plan_validity: 'Per Year',
//     plan_main_sub: '2 Number of Listings',
//     plan_sub_valid: '180 Days',
//   },
//   {
//     id: 4,
//     plan_type: 'Premium Plus',
//     plan_sub: '8X Response Rate',
//     plan_offer: '',
//     plan_prime: '4000',
//     plan_validity: 'Per Year',
//     plan_main_sub: '2 Number of Listings',
//     plan_sub_valid: '250 Days',
//   },
// ];

export const AgentPlanData = [
  {
    "id": 1,
    "name": "Free",
    "price": "",
    "plan_price": "",
    "period": "15",
    "response_rate": "Standard",
    "no_of_listings": "1",
    "whatsapp_notification": false,
    "featured_lisiting": false,
    "urgent_sale_tag": false,
    "certified_agent_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 2,
    "name": "Basic",
    "price": "2999",
    "plan_price": "999",
    "period": "30",
    "response_rate": "2x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "featured_lisiting": true,
    "urgent_sale_tag": false,
    "certified_agent_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 3,
    "name": "Standard",
    "price": "4999",
    "plan_price": "2999",
    "period": "120",
    "response_rate": "3x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "featured_lisiting": true,
    "urgent_sale_tag": true,
    "certified_agent_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 4,
    "name": "Premium",
    "price": "8999",
    "plan_price": "5999",
    "period": "180",
    "response_rate": "5x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "featured_lisiting": true,
    "urgent_sale_tag": false,
    "certified_agent_tag": true,
    "relationship_manager": true,
    "dedicated_support": false
  },
  {
    "id": 5,
    "name": "Premium Plus",
    "price": "19999",
    "plan_price": "14999",
    "period": "365",
    "response_rate": "10x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "featured_lisiting": true,
    "urgent_sale_tag": false,
    "certified_agent_tag": true,
    "relationship_manager": true,
    "dedicated_support": true
  }
];

export const OwnerPlanData = [
  {
    "id": 1,
    "name": "Free",
    "price": "",
    "plan_price": "",
    "period": "15",
    "response_rate": "Standard",
    "no_of_listings": "1",
    "whatsapp_notification": false,
    "highlighted_in_home_page": false,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 2,
    "name": "Basic",
    "price": "2999",
    "plan_price": "999",
    "period": "30",
    "response_rate": "2x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": false,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 3,
    "name": "Standard",
    "price": "4999",
    "plan_price": "2999",
    "period": "120",
    "response_rate": "3x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 4,
    "name": "Premium",
    "price": "8999",
    "plan_price": "5999",
    "period": "180",
    "response_rate": "5x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 5,
    "name": "We Plus",
    "price": "13999",
    "plan_price": "9999",
    "period": "250",
    "response_rate": "8x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": true,
    "dedicated_support": false
  },
  {
    "id": 6,
    "name": "Premium Plus",
    "price": "19999",
    "plan_price": "14999",
    "period": "365",
    "response_rate": "10x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": true,
    "dedicated_support": true
  }
];

export const BuilderPlanData = [
  {
    "id": 1,
    "name": "Free",
    "price": "",
    "plan_price": "",
    "period": "15",
    "response_rate": "Standard",
    "no_of_listings": "1",
    "whatsapp_notification": false,
    "highlighted_in_home_page": false,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 2,
    "name": "Basic",
    "price": "2999",
    "plan_price": "999",
    "period": "30",
    "response_rate": "2x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": false,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 3,
    "name": "Standard",
    "price": "4999",
    "plan_price": "2999",
    "period": "120",
    "response_rate": "3x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": false,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 4,
    "name": "Premium",
    "price": "8999",
    "plan_price": "5999",
    "period": "180",
    "response_rate": "5x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": false,
    "dedicated_support": false
  },
  {
    "id": 5,
    "name": "We Plus",
    "price": "13999",
    "plan_price": "9999",
    "period": "250",
    "response_rate": "8x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": true,
    "dedicated_support": false
  },
  {
    "id": 6,
    "name": "Premium Plus",
    "price": "19999",
    "plan_price": "14999",
    "period": "365",
    "response_rate": "10x",
    "no_of_listings": "2",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
    "verified_property_tag": true,
    "relationship_manager": true,
    "dedicated_support": true
  }
];

export const BuyerPlanData = [
  {
    "id": 1,
    "name": "Free",
    "plan_price": "NA",
    "period": "1 Month",
    "no_of_owner_numbers_can_be_viewed": "3",
    "whatsapp_notification": false,
    "highlighted_in_home_page": false,
  },
  
  {
    "id": 2,
    "name": "Bronze",
    "plan_price": "499",
    "period": "3 Month",
    "no_of_owner_numbers_can_be_viewed": "15",
    "whatsapp_notification": true,
    "highlighted_in_home_page": false,
  },
  {
    "id": 3,
    "name": "Silver",
    "plan_price": "999",
    "period": "3 Month",
    "no_of_owner_numbers_can_be_viewed": "40",
    "whatsapp_notification": true,
    "highlighted_in_home_page": false,
  },
  {
    "id": 4,
    "name": "Gold",
    "plan_price": "1999",
    "period": "3 Month",
    "no_of_owner_numbers_can_be_viewed": "70",
    "whatsapp_notification": true,
    "highlighted_in_home_page": true,
  },
];